//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenParcialLozano.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Jugadores
    {
        public int ID_Jugador { get; set; }
        [Display(Name = "Nombre ")]
        public string Nombre { get; set; }
        [Display(Name = "edad ")]
        public Nullable<int> Edad { get; set; }
        [Display(Name = "Goles ")]
        public Nullable<int> Goles { get; set; }
        [Display(Name = "asistencias ")]
        public Nullable<int> Asistencias { get; set; }
        [Display(Name = "id_equipo ")]
        public Nullable<int> ID_Equipo { get; set; }
        

        public virtual Equipos Equipos { get; set; }
    }
}
